#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

feh --bg-scale ~/img/wallpapers/tree-of-life-god.png
picom -b
~/.config/polybar/launch.sh

# startup layout (file in /tmp/ prevents this from running on config reloads)

if [ ! -e /tmp/bspwm_started ]; then
    bspc rule -a kitty:kitty_main -o desktop=I
    bspc rule -a kitty:kitty_sysmonitor -o desktop=I
    bspc rule -a kitty:kitty_ws5 -o desktop=V
    bspc rule -a kitty:kitty_music -o desktop=IX
    bspc rule -a kitty:kitty_irc -o desktop=X

    kitty --name kitty_main &
    kitty --name kitty_sysmonitor "$SHELL" -c "gotop; exec $SHELL -i" &
    kitty --name kitty_ws5 --session ~/.config/kitty/ws5.session &
    kitty --name kitty_music "$SHELL" -c "ncmpcpp; exec $SHELL -i" &
    kitty --name kitty_irc "$SHELL" -c "weechat; exec $SHELL -i" &

    bspc desktop -f I
    touch /tmp/bspwm_started
fi

# scratchpad

bspc rule -a kitty:kitty_scratchpad sticky=on state=floating hidden=on
pgrep -f kitty_scratchpad || kitty --name kitty_scratchpad -c ~/.config/kitty/scratchpad.conf ~/bin/scratchpad-launch.sh &
